// currencies.js – YouTube Studio tarafından desteklenen para birimleri
// countries: aksan-free arama terimleri (ülke adı / para birimi alternatif adları)
const KS_CURRENCIES = [
    { code: "AED", name: "Birleşik Arap Emirlikleri dirhemi", countries: "bae dubai abu dhabi emirates arab" },
    { code: "ARS", name: "Arjantin pesosu",                  countries: "arjantin argentina" },
    { code: "AUD", name: "Avustralya doları",                countries: "avustralya australia" },
    { code: "BHD", name: "Bahreyn dinarı",                   countries: "bahreyn bahrain" },
    { code: "BRL", name: "Brezilya reali",                   countries: "brezilya brazil brasil" },
    { code: "CAD", name: "Kanada doları",                    countries: "kanada canada" },
    { code: "CHF", name: "İsviçre frangı",                   countries: "isvicre switzerland schweiz" },
    { code: "CLP", name: "Şili pesosu",                      countries: "sili chile" },
    { code: "CNY", name: "Çin yuanı",                        countries: "cin china zhongguo renminbi" },
    { code: "COP", name: "Kolombiya pesosu",                 countries: "kolombiya colombia" },
    { code: "CZK", name: "Çek korunası",                     countries: "cek cumhuriyeti czech republic czechia" },
    { code: "DKK", name: "Danimarka kronu",                  countries: "danimarka denmark danmark" },
    { code: "DZD", name: "Cezayir dinarı",                   countries: "cezayir algeria algerie" },
    { code: "EGP", name: "Mısır poundu",                     countries: "misir egypt misr" },
    { code: "EUR", name: "Euro",                             countries: "avrupa europe eurozone ab" },
    { code: "GBP", name: "İngiliz sterlini",                 countries: "ingiltere uk united kingdom britain sterling pound" },
    { code: "GEL", name: "Gürcistan larisi",                 countries: "gurcistan georgia" },
    { code: "HKD", name: "Hong Kong doları",                 countries: "hong kong" },
    { code: "HNL", name: "Honduras lempirası",               countries: "honduras" },
    { code: "HUF", name: "Macar forinti",                    countries: "macaristan hungary magyarorszag" },
    { code: "IDR", name: "Endonezya rupisi",                 countries: "endonezya indonesia" },
    { code: "ILS", name: "İsrail şekeli",                    countries: "israil israel shekel" },
    { code: "INR", name: "Hindistan rupisi",                 countries: "hindistan india rupee" },
    { code: "ISK", name: "İzlanda kronası",                  countries: "izlanda iceland" },
    { code: "JPY", name: "Japon yeni",                       countries: "japonya japan nippon yen" },
    { code: "KES", name: "Kenya şilini",                     countries: "kenya" },
    { code: "KRW", name: "Güney Kore wonu",                  countries: "guney kore south korea hanguk won" },
    { code: "KWD", name: "Kuveyt dinarı",                    countries: "kuveyt kuwait" },
    { code: "KZT", name: "Kazakistan tengesi",               countries: "kazakistan kazakhstan" },
    { code: "MAD", name: "Fas dirhemi",                      countries: "fas morocco maroc" },
    { code: "MUR", name: "Mauritius rupisi",                 countries: "mauritius" },
    { code: "MVR", name: "Maldivler rufiyaası",              countries: "maldivler maldives" },
    { code: "MXN", name: "Meksika pesosu",                   countries: "meksika mexico" },
    { code: "MYR", name: "Malezya ringgiti",                 countries: "malezya malaysia ringgit" },
    { code: "NGN", name: "Nijerya nairası",                  countries: "nijerya nigeria naira" },
    { code: "NOK", name: "Norveç kronu",                     countries: "norvec norway norge" },
    { code: "NZD", name: "Yeni Zelanda doları",              countries: "yeni zelanda new zealand" },
    { code: "OMR", name: "Umman riyali",                     countries: "umman oman" },
    { code: "PAB", name: "Panama balboası",                  countries: "panama" },
    { code: "PEN", name: "Peru solu",                        countries: "peru" },
    { code: "PHP", name: "Filipinler pesosu",                countries: "filipinler philippines pilipinas" },
    { code: "PKR", name: "Pakistan rupisi",                  countries: "pakistan" },
    { code: "PLN", name: "Polonya zlotısı",                  countries: "polonya poland polska zloty" },
    { code: "QAR", name: "Katar riyali",                     countries: "katar qatar" },
    { code: "RON", name: "Romanya leyi",                     countries: "romanya romania" },
    { code: "RSD", name: "Sırbistan dinarı",                 countries: "sirbistan serbia srbija" },
    { code: "RUB", name: "Rus rublesi",                      countries: "rusya russia rossiya ruble" },
    { code: "SAR", name: "Suudi Arabistan riyali",           countries: "suudi arabistan saudi arabia ksa" },
    { code: "SEK", name: "İsveç kronu",                      countries: "isvec sweden sverige" },
    { code: "SGD", name: "Singapur doları",                  countries: "singapur singapore" },
    { code: "THB", name: "Tayland bahtı",                    countries: "tayland thailand baht" },
    { code: "TND", name: "Tunus dinarı",                     countries: "tunus tunisia" },
    { code: "TRY", name: "Türk lirası",                      countries: "turkiye turkey turk lira" },
    { code: "TWD", name: "Tayvan yeni doları",               countries: "tayvan taiwan" },
    { code: "UAH", name: "Ukrayna grivnası",                 countries: "ukrayna ukraine hryvnia" },
    { code: "USD", name: "ABD doları",                       countries: "abd amerika america united states usa dollar" },
    { code: "UYU", name: "Uruguay pesosu",                   countries: "uruguay" },
    { code: "ZAR", name: "Güney Afrika randı",               countries: "guney afrika south africa rand" }
];
